/*
 * generated by Xtext 2.28.0
 */
package arg.parser.antlr;

import arg.parser.antlr.internal.InternalArgParser;
import arg.services.ArgGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ArgParser extends AbstractAntlrParser {

	@Inject
	private ArgGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArgParser createParser(XtextTokenStream stream) {
		return new InternalArgParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Ontological";
	}

	public ArgGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
