/*
 * generated by Xtext 2.28.0
 */
package arg.ide.contentassist.antlr;

import arg.ide.contentassist.antlr.internal.InternalArgParser;
import arg.services.ArgGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ArgParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ArgGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ArgGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getAttributeMaxAccess().getAlternatives(), "rule__AttributeMax__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getNoLimitAccess().getAlternatives(), "rule__NoLimit__Alternatives");
			builder.put(grammarAccess.getPosOrCameraAccess().getAlternatives(), "rule__PosOrCamera__Alternatives");
			builder.put(grammarAccess.getConstantAccess().getAlternatives(), "rule__Constant__Alternatives");
			builder.put(grammarAccess.getGestureAccess().getAlternatives(), "rule__Gesture__Alternatives");
			builder.put(grammarAccess.getPlanesAccess().getAlternatives(), "rule__Planes__Alternatives");
			builder.put(grammarAccess.getBodyTypeAccess().getAlternatives(), "rule__BodyType__Alternatives");
			builder.put(grammarAccess.getBasicActionsAccess().getAlternatives(), "rule__BasicActions__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
			builder.put(grammarAccess.getLogicOpsAccess().getAlternatives(), "rule__LogicOps__Alternatives");
			builder.put(grammarAccess.getArithmOpsAccess().getAlternatives(), "rule__ArithmOps__Alternatives");
			builder.put(grammarAccess.getOntologicalAccess().getGroup(), "rule__Ontological__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
			builder.put(grammarAccess.getClassAccess().getGroup_2(), "rule__Class__Group_2__0");
			builder.put(grammarAccess.getClassAccess().getGroup_3(), "rule__Class__Group_3__0");
			builder.put(grammarAccess.getGraphicAccess().getGroup(), "rule__Graphic__Group__0");
			builder.put(grammarAccess.getPhysicAccess().getGroup(), "rule__Physic__Group__0");
			builder.put(grammarAccess.getGameAccess().getGroup(), "rule__Game__Group__0");
			builder.put(grammarAccess.getGameAccess().getGroup_15(), "rule__Game__Group_15__0");
			builder.put(grammarAccess.getGameAccess().getGroup_16(), "rule__Game__Group_16__0");
			builder.put(grammarAccess.getGameAccess().getGroup_17(), "rule__Game__Group_17__0");
			builder.put(grammarAccess.getGameAccess().getGroup_18(), "rule__Game__Group_18__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_1(), "rule__Reference__Group_1__0");
			builder.put(grammarAccess.getReferenceAccess().getGroup_8(), "rule__Reference__Group_8__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getGraphicClassAccess().getGroup(), "rule__GraphicClass__Group__0");
			builder.put(grammarAccess.getConstraintsAccess().getGroup(), "rule__Constraints__Group__0");
			builder.put(grammarAccess.getConnectionAccess().getGroup(), "rule__Connection__Group__0");
			builder.put(grammarAccess.getVersionsAccess().getGroup(), "rule__Versions__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getPhysicClassAccess().getGroup(), "rule__PhysicClass__Group__0");
			builder.put(grammarAccess.getPhysicClassAccess().getGroup_6(), "rule__PhysicClass__Group_6__0");
			builder.put(grammarAccess.getPhysicClassAccess().getGroup_7(), "rule__PhysicClass__Group_7__0");
			builder.put(grammarAccess.getPhysicBodyAccess().getGroup(), "rule__PhysicBody__Group__0");
			builder.put(grammarAccess.getBitMasksAccess().getGroup(), "rule__BitMasks__Group__0");
			builder.put(grammarAccess.getForceAccess().getGroup(), "rule__Force__Group__0");
			builder.put(grammarAccess.getForceAccess().getGroup_4(), "rule__Force__Group_4__0");
			builder.put(grammarAccess.getGamePadAccess().getGroup(), "rule__GamePad__Group__0");
			builder.put(grammarAccess.getScoreSystemAccess().getGroup(), "rule__ScoreSystem__Group__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup(), "rule__Trigger__Group__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup_2(), "rule__Trigger__Group_2__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup_3(), "rule__Trigger__Group_3__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup_4(), "rule__Trigger__Group_4__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup_5(), "rule__Trigger__Group_5__0");
			builder.put(grammarAccess.getTriggerAccess().getGroup_6(), "rule__Trigger__Group_6__0");
			builder.put(grammarAccess.getCollisionAccess().getGroup(), "rule__Collision__Group__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup(), "rule__ObjInit__Group__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_9(), "rule__ObjInit__Group_9__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_11(), "rule__ObjInit__Group_11__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_11_3(), "rule__ObjInit__Group_11_3__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_12(), "rule__ObjInit__Group_12__0");
			builder.put(grammarAccess.getObjInitAccess().getGroup_12_3(), "rule__ObjInit__Group_12_3__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup(), "rule__PhysicChange__Group__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup_2(), "rule__PhysicChange__Group_2__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup_5(), "rule__PhysicChange__Group_5__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup_6(), "rule__PhysicChange__Group_6__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup_7(), "rule__PhysicChange__Group_7__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup_8(), "rule__PhysicChange__Group_8__0");
			builder.put(grammarAccess.getPhysicChangeAccess().getGroup_9(), "rule__PhysicChange__Group_9__0");
			builder.put(grammarAccess.getObjAttributeAccess().getGroup(), "rule__ObjAttribute__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getNotAccess().getGroup(), "rule__Not__Group__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup(), "rule__Binary__Group__0");
			builder.put(grammarAccess.getArithmeticAccess().getGroup(), "rule__Arithmetic__Group__0");
			builder.put(grammarAccess.getAttributeValueAccess().getGroup(), "rule__AttributeValue__Group__0");
			builder.put(grammarAccess.getAllInstancesAccess().getGroup(), "rule__AllInstances__Group__0");
			builder.put(grammarAccess.getOntologicalAccess().getNameAssignment_1(), "rule__Ontological__NameAssignment_1");
			builder.put(grammarAccess.getOntologicalAccess().getClassesAssignment_5(), "rule__Ontological__ClassesAssignment_5");
			builder.put(grammarAccess.getOntologicalAccess().getClassesAssignment_6(), "rule__Ontological__ClassesAssignment_6");
			builder.put(grammarAccess.getOntologicalAccess().getGraphicAssignment_9(), "rule__Ontological__GraphicAssignment_9");
			builder.put(grammarAccess.getOntologicalAccess().getPhysicAssignment_10(), "rule__Ontological__PhysicAssignment_10");
			builder.put(grammarAccess.getOntologicalAccess().getGameAssignment_11(), "rule__Ontological__GameAssignment_11");
			builder.put(grammarAccess.getClassAccess().getNameAssignment_0(), "rule__Class__NameAssignment_0");
			builder.put(grammarAccess.getClassAccess().getAttributesAssignment_2_0(), "rule__Class__AttributesAssignment_2_0");
			builder.put(grammarAccess.getClassAccess().getAttributesAssignment_2_1(), "rule__Class__AttributesAssignment_2_1");
			builder.put(grammarAccess.getClassAccess().getReferencesAssignment_3_2(), "rule__Class__ReferencesAssignment_3_2");
			builder.put(grammarAccess.getClassAccess().getReferencesAssignment_3_3(), "rule__Class__ReferencesAssignment_3_3");
			builder.put(grammarAccess.getClassAccess().getAbstractAssignment_5(), "rule__Class__AbstractAssignment_5");
			builder.put(grammarAccess.getClassAccess().getNoSCNAssignment_6(), "rule__Class__NoSCNAssignment_6");
			builder.put(grammarAccess.getGraphicAccess().getClassesAssignment_2(), "rule__Graphic__ClassesAssignment_2");
			builder.put(grammarAccess.getGraphicAccess().getClassesAssignment_3(), "rule__Graphic__ClassesAssignment_3");
			builder.put(grammarAccess.getPhysicAccess().getClassesAssignment_2(), "rule__Physic__ClassesAssignment_2");
			builder.put(grammarAccess.getPhysicAccess().getClassesAssignment_3(), "rule__Physic__ClassesAssignment_3");
			builder.put(grammarAccess.getGameAccess().getStartAssignment_5(), "rule__Game__StartAssignment_5");
			builder.put(grammarAccess.getGameAccess().getWinAssignment_7(), "rule__Game__WinAssignment_7");
			builder.put(grammarAccess.getGameAccess().getLoseAssignment_9(), "rule__Game__LoseAssignment_9");
			builder.put(grammarAccess.getGameAccess().getScoreAssignment_12(), "rule__Game__ScoreAssignment_12");
			builder.put(grammarAccess.getGameAccess().getActionsTriggersAssignment_15_2(), "rule__Game__ActionsTriggersAssignment_15_2");
			builder.put(grammarAccess.getGameAccess().getActionsTriggersAssignment_15_3(), "rule__Game__ActionsTriggersAssignment_15_3");
			builder.put(grammarAccess.getGameAccess().getCollisionsAssignment_16_2(), "rule__Game__CollisionsAssignment_16_2");
			builder.put(grammarAccess.getGameAccess().getCollisionsAssignment_16_3(), "rule__Game__CollisionsAssignment_16_3");
			builder.put(grammarAccess.getGameAccess().getGamepadAssignment_17_2(), "rule__Game__GamepadAssignment_17_2");
			builder.put(grammarAccess.getGameAccess().getGamepadAssignment_17_3(), "rule__Game__GamepadAssignment_17_3");
			builder.put(grammarAccess.getGameAccess().getObjInitAssignment_18_2(), "rule__Game__ObjInitAssignment_18_2");
			builder.put(grammarAccess.getGameAccess().getObjInitAssignment_18_3(), "rule__Game__ObjInitAssignment_18_3");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
			builder.put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
			builder.put(grammarAccess.getAttributeAccess().getMinAssignment_4(), "rule__Attribute__MinAssignment_4");
			builder.put(grammarAccess.getAttributeAccess().getMaxAssignment_6(), "rule__Attribute__MaxAssignment_6");
			builder.put(grammarAccess.getAttributeAccess().getDefaultAssignment_9(), "rule__Attribute__DefaultAssignment_9");
			builder.put(grammarAccess.getAttributeAccess().getIsParamAssignment_10(), "rule__Attribute__IsParamAssignment_10");
			builder.put(grammarAccess.getAttributeAccess().getIsKeyAssignment_11(), "rule__Attribute__IsKeyAssignment_11");
			builder.put(grammarAccess.getAttributeAccess().getReadOnlyAssignment_12(), "rule__Attribute__ReadOnlyAssignment_12");
			builder.put(grammarAccess.getReferenceAccess().getNameAssignment_0(), "rule__Reference__NameAssignment_0");
			builder.put(grammarAccess.getReferenceAccess().getContaintmentAssignment_1_1(), "rule__Reference__ContaintmentAssignment_1_1");
			builder.put(grammarAccess.getReferenceAccess().getMinAssignment_3(), "rule__Reference__MinAssignment_3");
			builder.put(grammarAccess.getReferenceAccess().getMaxAssignment_5(), "rule__Reference__MaxAssignment_5");
			builder.put(grammarAccess.getReferenceAccess().getTargetAssignment_7(), "rule__Reference__TargetAssignment_7");
			builder.put(grammarAccess.getReferenceAccess().getOppositeAssignment_8_1(), "rule__Reference__OppositeAssignment_8_1");
			builder.put(grammarAccess.getGraphicClassAccess().getOntoClassAssignment_1(), "rule__GraphicClass__OntoClassAssignment_1");
			builder.put(grammarAccess.getGraphicClassAccess().getVersionsAssignment_4(), "rule__GraphicClass__VersionsAssignment_4");
			builder.put(grammarAccess.getGraphicClassAccess().getVersionsAssignment_5(), "rule__GraphicClass__VersionsAssignment_5");
			builder.put(grammarAccess.getGraphicClassAccess().getConstraintsAssignment_9(), "rule__GraphicClass__ConstraintsAssignment_9");
			builder.put(grammarAccess.getConstraintsAccess().getPlanesAssignment_1(), "rule__Constraints__PlanesAssignment_1");
			builder.put(grammarAccess.getConstraintsAccess().getOverlappingAssignment_2(), "rule__Constraints__OverlappingAssignment_2");
			builder.put(grammarAccess.getConstraintsAccess().getSizeMinAssignment_4(), "rule__Constraints__SizeMinAssignment_4");
			builder.put(grammarAccess.getConstraintsAccess().getSizeMaxAssignment_6(), "rule__Constraints__SizeMaxAssignment_6");
			builder.put(grammarAccess.getConstraintsAccess().getXToOriginPosAssignment_8(), "rule__Constraints__XToOriginPosAssignment_8");
			builder.put(grammarAccess.getConstraintsAccess().getYToOriginPosAssignment_10(), "rule__Constraints__YToOriginPosAssignment_10");
			builder.put(grammarAccess.getConstraintsAccess().getZToOriginPosAssignment_12(), "rule__Constraints__ZToOriginPosAssignment_12");
			builder.put(grammarAccess.getConstraintsAccess().getRotationAssignment_14(), "rule__Constraints__RotationAssignment_14");
			builder.put(grammarAccess.getConnectionAccess().getNameAssignment_1(), "rule__Connection__NameAssignment_1");
			builder.put(grammarAccess.getConnectionAccess().getTypeAssignment_4(), "rule__Connection__TypeAssignment_4");
			builder.put(grammarAccess.getConnectionAccess().getColorAssignment_6(), "rule__Connection__ColorAssignment_6");
			builder.put(grammarAccess.getConnectionAccess().getTextColorAssignment_8(), "rule__Connection__TextColorAssignment_8");
			builder.put(grammarAccess.getConnectionAccess().getDecoratorAssignment_10(), "rule__Connection__DecoratorAssignment_10");
			builder.put(grammarAccess.getConnectionAccess().getDecoratorPosAssignment_12(), "rule__Connection__DecoratorPosAssignment_12");
			builder.put(grammarAccess.getConnectionAccess().getPatternAssignment_14(), "rule__Connection__PatternAssignment_14");
			builder.put(grammarAccess.getConnectionAccess().getWidthAssignment_16(), "rule__Connection__WidthAssignment_16");
			builder.put(grammarAccess.getConnectionAccess().getPositionAssignment_18(), "rule__Connection__PositionAssignment_18");
			builder.put(grammarAccess.getVersionsAccess().getNameAssignment_0(), "rule__Versions__NameAssignment_0");
			builder.put(grammarAccess.getVersionsAccess().getURLAssignment_2(), "rule__Versions__URLAssignment_2");
			builder.put(grammarAccess.getPhysicClassAccess().getOntoClassAssignment_1(), "rule__PhysicClass__OntoClassAssignment_1");
			builder.put(grammarAccess.getPhysicClassAccess().getPhysicBodyAssignment_4(), "rule__PhysicClass__PhysicBodyAssignment_4");
			builder.put(grammarAccess.getPhysicClassAccess().getForcesAssignment_6_2(), "rule__PhysicClass__ForcesAssignment_6_2");
			builder.put(grammarAccess.getPhysicClassAccess().getForcesAssignment_6_3(), "rule__PhysicClass__ForcesAssignment_6_3");
			builder.put(grammarAccess.getPhysicClassAccess().getBitMasksAssignment_7_2(), "rule__PhysicClass__BitMasksAssignment_7_2");
			builder.put(grammarAccess.getPhysicBodyAccess().getMassAssignment_1(), "rule__PhysicBody__MassAssignment_1");
			builder.put(grammarAccess.getPhysicBodyAccess().getBodyTypeAssignment_3(), "rule__PhysicBody__BodyTypeAssignment_3");
			builder.put(grammarAccess.getPhysicBodyAccess().getChargeAssignment_5(), "rule__PhysicBody__ChargeAssignment_5");
			builder.put(grammarAccess.getPhysicBodyAccess().getFrictionAssignment_7(), "rule__PhysicBody__FrictionAssignment_7");
			builder.put(grammarAccess.getPhysicBodyAccess().getRollingFrictionAssignment_9(), "rule__PhysicBody__RollingFrictionAssignment_9");
			builder.put(grammarAccess.getPhysicBodyAccess().getRestitutionAssignment_11(), "rule__PhysicBody__RestitutionAssignment_11");
			builder.put(grammarAccess.getPhysicBodyAccess().getDampingAssignment_13(), "rule__PhysicBody__DampingAssignment_13");
			builder.put(grammarAccess.getPhysicBodyAccess().getAngularDampingAssignment_15(), "rule__PhysicBody__AngularDampingAssignment_15");
			builder.put(grammarAccess.getBitMasksAccess().getCollisionAssignment_1(), "rule__BitMasks__CollisionAssignment_1");
			builder.put(grammarAccess.getBitMasksAccess().getCollisionAssignment_2(), "rule__BitMasks__CollisionAssignment_2");
			builder.put(grammarAccess.getBitMasksAccess().getContactAssignment_4(), "rule__BitMasks__ContactAssignment_4");
			builder.put(grammarAccess.getBitMasksAccess().getContactAssignment_5(), "rule__BitMasks__ContactAssignment_5");
			builder.put(grammarAccess.getForceAccess().getNameAssignment_0(), "rule__Force__NameAssignment_0");
			builder.put(grammarAccess.getForceAccess().getGestureAssignment_3(), "rule__Force__GestureAssignment_3");
			builder.put(grammarAccess.getForceAccess().getXVectorAssignment_4_1(), "rule__Force__XVectorAssignment_4_1");
			builder.put(grammarAccess.getForceAccess().getYVectorAssignment_4_3(), "rule__Force__YVectorAssignment_4_3");
			builder.put(grammarAccess.getForceAccess().getZVectorAssignment_4_5(), "rule__Force__ZVectorAssignment_4_5");
			builder.put(grammarAccess.getGamePadAccess().getNameAssignment_0(), "rule__GamePad__NameAssignment_0");
			builder.put(grammarAccess.getGamePadAccess().getTriggerAssignment_2(), "rule__GamePad__TriggerAssignment_2");
			builder.put(grammarAccess.getScoreSystemAccess().getStartAssignment_1(), "rule__ScoreSystem__StartAssignment_1");
			builder.put(grammarAccess.getScoreSystemAccess().getFinishAssignment_3(), "rule__ScoreSystem__FinishAssignment_3");
			builder.put(grammarAccess.getScoreSystemAccess().getLivesAssignment_5(), "rule__ScoreSystem__LivesAssignment_5");
			builder.put(grammarAccess.getTriggerAccess().getNameAssignment_0(), "rule__Trigger__NameAssignment_0");
			builder.put(grammarAccess.getTriggerAccess().getActionAssignment_2_1(), "rule__Trigger__ActionAssignment_2_1");
			builder.put(grammarAccess.getTriggerAccess().getMessageAssignment_3_1(), "rule__Trigger__MessageAssignment_3_1");
			builder.put(grammarAccess.getTriggerAccess().getScoreChangeAssignment_4_1(), "rule__Trigger__ScoreChangeAssignment_4_1");
			builder.put(grammarAccess.getTriggerAccess().getTimeTriggerAssignment_5_1(), "rule__Trigger__TimeTriggerAssignment_5_1");
			builder.put(grammarAccess.getTriggerAccess().getPhysicChangesAssignment_6_2(), "rule__Trigger__PhysicChangesAssignment_6_2");
			builder.put(grammarAccess.getTriggerAccess().getPhysicChangesAssignment_6_3(), "rule__Trigger__PhysicChangesAssignment_6_3");
			builder.put(grammarAccess.getCollisionAccess().getClassAAssignment_1(), "rule__Collision__ClassAAssignment_1");
			builder.put(grammarAccess.getCollisionAccess().getClassBAssignment_3(), "rule__Collision__ClassBAssignment_3");
			builder.put(grammarAccess.getCollisionAccess().getActionAssignment_5(), "rule__Collision__ActionAssignment_5");
			builder.put(grammarAccess.getObjInitAccess().getNameAssignment_0(), "rule__ObjInit__NameAssignment_0");
			builder.put(grammarAccess.getObjInitAccess().getClassAssignment_2(), "rule__ObjInit__ClassAssignment_2");
			builder.put(grammarAccess.getObjInitAccess().getPosXAssignment_4(), "rule__ObjInit__PosXAssignment_4");
			builder.put(grammarAccess.getObjInitAccess().getPosYAssignment_6(), "rule__ObjInit__PosYAssignment_6");
			builder.put(grammarAccess.getObjInitAccess().getPosZAssignment_8(), "rule__ObjInit__PosZAssignment_8");
			builder.put(grammarAccess.getObjInitAccess().getRotationAssignment_9_1(), "rule__ObjInit__RotationAssignment_9_1");
			builder.put(grammarAccess.getObjInitAccess().getAttributeAssignment_11_2(), "rule__ObjInit__AttributeAssignment_11_2");
			builder.put(grammarAccess.getObjInitAccess().getAttributeAssignment_11_3_1(), "rule__ObjInit__AttributeAssignment_11_3_1");
			builder.put(grammarAccess.getObjInitAccess().getRulesAssignment_12_2(), "rule__ObjInit__RulesAssignment_12_2");
			builder.put(grammarAccess.getObjInitAccess().getRulesAssignment_12_3_1(), "rule__ObjInit__RulesAssignment_12_3_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getActionAssignment_1(), "rule__PhysicChange__ActionAssignment_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getClassAssignment_2_1(), "rule__PhysicChange__ClassAssignment_2_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getObjectAssignment_4(), "rule__PhysicChange__ObjectAssignment_4");
			builder.put(grammarAccess.getPhysicChangeAccess().getPositionAssignment_5_1(), "rule__PhysicChange__PositionAssignment_5_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getScaleAssignment_6_1(), "rule__PhysicChange__ScaleAssignment_6_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getAttributeAssignment_7_1(), "rule__PhysicChange__AttributeAssignment_7_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getChangeValueAssignment_8_1(), "rule__PhysicChange__ChangeValueAssignment_8_1");
			builder.put(grammarAccess.getPhysicChangeAccess().getForceAssignment_9_1(), "rule__PhysicChange__ForceAssignment_9_1");
			builder.put(grammarAccess.getObjAttributeAccess().getAttributeAssignment_0(), "rule__ObjAttribute__AttributeAssignment_0");
			builder.put(grammarAccess.getObjAttributeAccess().getValueAssignment_2(), "rule__ObjAttribute__ValueAssignment_2");
			builder.put(grammarAccess.getRuleAccess().getActionAssignment_1(), "rule__Rule__ActionAssignment_1");
			builder.put(grammarAccess.getRuleAccess().getConditionAssignment_3(), "rule__Rule__ConditionAssignment_3");
			builder.put(grammarAccess.getNotAccess().getLeftAssignment_1(), "rule__Not__LeftAssignment_1");
			builder.put(grammarAccess.getBinaryAccess().getLeftAssignment_1(), "rule__Binary__LeftAssignment_1");
			builder.put(grammarAccess.getBinaryAccess().getOpAssignment_3(), "rule__Binary__OpAssignment_3");
			builder.put(grammarAccess.getBinaryAccess().getRightAssignment_5(), "rule__Binary__RightAssignment_5");
			builder.put(grammarAccess.getArithmeticAccess().getLeftAssignment_0(), "rule__Arithmetic__LeftAssignment_0");
			builder.put(grammarAccess.getArithmeticAccess().getOpAssignment_1(), "rule__Arithmetic__OpAssignment_1");
			builder.put(grammarAccess.getArithmeticAccess().getRightAssignment_2(), "rule__Arithmetic__RightAssignment_2");
			builder.put(grammarAccess.getAttributeValueAccess().getClassAssignment_0(), "rule__AttributeValue__ClassAssignment_0");
			builder.put(grammarAccess.getAttributeValueAccess().getAttributeAssignment_2(), "rule__AttributeValue__AttributeAssignment_2");
			builder.put(grammarAccess.getConstantValueAccess().getValueAssignment(), "rule__ConstantValue__ValueAssignment");
			builder.put(grammarAccess.getAllInstancesAccess().getTypeAssignment_1(), "rule__AllInstances__TypeAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ArgGrammarAccess grammarAccess;

	@Override
	protected InternalArgParser createParser() {
		InternalArgParser result = new InternalArgParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ArgGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArgGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
