/*
 * generated by Xtext 2.28.0
 */
package arg.ide;

import arg.ArgRuntimeModule;
import arg.ArgStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ArgIdeSetup extends ArgStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ArgRuntimeModule(), new ArgIdeModule()));
	}
	
}
