/*
 * generated by Xtext 2.28.0
 */
package arg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArgUiModule extends AbstractArgUiModule {

	public ArgUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
